## RDP connection details
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

version: 0.1.0-0.dev.{build}
branches:
  only:
  - master
image: Visual Studio 2017

clone_folder: c:\projects\NWheels
  
before_build:
- cmd: >-
    cd c:\projects\NWheels\Source2

    dotnet --version

    dotnet restore
build_script:
- cmd: >-
    dotnet build -c Release 

test_script:
- cmd: >-
    cd c:\projects\NWheels\Source2
    
    dotnet test NWheels.Kernel.UnitTests
    
    dotnet test NWheels.Compilation.UnitTests    

    dotnet test NWheels.MetaObjects.UnitTests    

after_test:
- cmd: >-
    cd c:\projects\NWheels\Source2

    echo %APPVEYOR_BUILD_VERSION%
    
    dotnet pack -c Release -p:Version=%APPVEYOR_BUILD_VERSION%

on_success:
- cmd: >-
    appveyor PushArtifact NWheels.Kernel\bin\Release\NWheels.Kernel.%APPVEYOR_BUILD_VERSION%.nupkg
    
    appveyor PushArtifact NWheels.Compilation\bin\Release\NWheels.Compilation.%APPVEYOR_BUILD_VERSION%.nupkg
    
    appveyor PushArtifact NWheels.MetaObjects\bin\Release\NWheels.MetaObjects.%APPVEYOR_BUILD_VERSION%.nupkg
    
## Pause build until file from desktop will be removed
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))    