## RDP connection details
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

version: 0.1.0-0.dev.{build}

branches:
  only:
  - master

image: Visual Studio 2017

clone_folder: c:\projects\NWheels

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.0.{build}"
  assembly_file_version: "0.1.0.{build}"
  assembly_informational_version: "{version}"

dotnet_csproj:
  patch: true
  file: "**\*.csproj"
  version: "0.1.0.{build}"
  package_version: "{version}"

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: false

before_build:
- cmd: >-
    cd c:\projects\NWheels\Source2

    dotnet --version

    dotnet restore

test_script:
- cmd: >-
    cd c:\projects\NWheels\Source2
    
    dotnet test NWheels.Kernel.UnitTests
    
    dotnet test NWheels.Compilation.UnitTests    

    dotnet test NWheels.MetaObjects.UnitTests    

## Pause build until file from desktop will be removed
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))    